README.rst, material/admin/templatetags/material_admin.py
An additional option for custom admin site object. 
It's a first step that can allow basic customization for users with custom admin site. Another solution could be to get inspiration from grappelli dashboard customization module. 
Default is the current behavior : using django admin site object.
I also updated the doc to mention this new option but I don't know if it's the right place.
=> Add support for custom admin site import instead of default django one.

README.rst
Well, I was using it with forms and the fields were not working as I expected with Materialize. Took me hours to realize that this needed jQuery and it was not included in the documentation.
I hope this would save time to other people.
=> Included jQuery in form-docs

material/admin/templates/admin/change_list.html
Hi,
This PR hides the filter div in the admin change_list if there no filter, date_hierarchy or search fields set on the admin.
Hope you like it !
Olivier
=> in admin change_list, the filter div is not shown not necessary

material/admin/templates/admin/change_list_results.html
Hi,
This PR adds sorting to the admin change_list by clicking on headers, partially fixing #106
The implementation is simpler than in Django's native admin list, as this doesn't display the ordering priorities in case the user sorts by multiple columns.
Hope you like it !
Olivier
=> added sorting in admin change_list by clicking on headers

material/admin/templatetags/material_admin.py
Fix pagination display bug.
There's another bug at the bottom of the changelist : the column headers are repeated outside of the table. I don't understand where it comes from.
=> fix pagination display bug

material/templates/material/includes/material_css.html
My setup with bare django 1.10 and django-material has the problem with the links
=> Remove whitespace at the end of some links

material/admin/templates/material/admin/edit_inline/stacked.html, material/admin/templates/material/admin/edit_inline/tabular.html
I made a small fix to display readonly strings that are marked safe as is in TabularInline and StackedInline.
=> Fixed display of safe readonly fields in TabularInline, StackedInline

material/admin/templates/material/fields/django_adminreadonlyfield.html
This branch fixes #187.  The issue was originally caused by a typo https://github.com/viewflow/django-material/commit/04ae12d4066efd3022b68c9535147a4444e39c6b where `fieldset_field.contents` got changed to `field.contents`.  This branch changes that text back.
-[x] Declared `readonly_fields` in ModelAdmin and asserted that fields were correctly populated and disabled
-[x] Removed fields from `readonly_fields` declaration and asserted that fields were correctly populated and *not* disabled
=> Fixed readonly admin field template bug

material/admin/templates/admin/submit_line.html
Commit 4e3e3d5e387 added extra save options to admin templates but left out "save as new" for no clear reason. This PR just corrects that.
=> Add "save as new" option to admin template

material/admin/templates/admin/login.html
Hello,
I was using the library and found a little bug. If you try to log in at the admin using /admin/login/, instead of (admin/login/?next=/admin/) it will redirect you to the url you define at LOGIN_REDIRECT_URL settings. This is produced because at your admin/login.html you are missing the following line inside the form
`<input type="hidden" name="next" value="{{ next }}" />`
you may see it [here](https://github.com/django/django/blob/master/django/contrib/admin/templates/admin/login.html), line 52.
Django's login looks for the next parameter to redirect, else it will use LOGIN_REDIRECT_URL to get the redirect url.
This little pull request should fix this problem.
Thank you
=> added next parameter to avoid bad redirection at admin

MANIFEST.in
The `MANIFEST.in` points to `LICENSE` instead of `LICENSE.txt` so the license file is not included in the source distribution.
=> Fix LICENSE in MANIFEST.in

material/frontend/templates/material/frontend/views/detail.html, material/frontend/views/detail.py
if the field is a `ForeignKey`, `field.get_attname()` return the name of the column instead of the actual field (ie, for a fk named `medio`, it returns `"medio_id"`). Then, the `pk` of the related object is returned instead of the actual object, and it looks like this in the detail view. 
With this change the object is returned, thus its `__str__` is used to display it.
=> return the actual related object instead the id

material/admin/templatetags/material_admin.py
Reduced number of django templates warnings for missing 'active' variable in request context.
=> Reduced number of django templates warnings

material/templates/material/fields/django_selectmultiple.html, material/templatetags/material_form.py
Currently the boolean attribute `multiple` of a select element is rendered incorrectly as follows:
`<select multiple="True">..</select>`
`"True"` is not a valid value for a [boolean attribute](https://stackoverflow.com/questions/4139786/what-does-it-mean-in-html-5-when-an-attribute-is-a-boolean-attribute#answer-4140263). With this pull request I've converted it to the correct value `"multiple"`. Another options would have been to set it to empty as the value `""` is also valid.
=> Fix boolean attribute value

material/templates/material/fields/django_fileinput.html
Hi there! Thanks for your great library)
Recently I needed custom multiple file upload field in form. I find out that all widget attributes go to file path wrapper, but not to button itself. So I decided to at least add this attribute to button and came out with this tiny pull request.
Field from my ModelForm:
```
...
attachments = forms.FileField(required=False, widget=forms.ClearableFileInput(attrs={'multiple': True}))
...
```
=> FileField fix multiple files

material/templates/material/fields/django_input.html, tests/test_widget_textinput.py
Since Django 1.9 a form field can be declared as disabled:
https://docs.djangoproject.com/en/dev/ref/forms/fields/#disabled
However these are not rendered as disabled by django-material. This patch fixes it for input fields.
=> Handle disabled input fields

material/templates/material/form.html, material/templates/material/non_field_errors.html
I added this part to make it easier to customize error messages generated by `django-material` without the need to change the whole template code of `form.html`.
=> Make non field errors easier to customize

material/frontend/views/list.py
There is a small typo in material/frontend/views/list.py.
Should read `external` rather than `extenal`.
=> docs: Fix simple typo, extenal -> external

material/frontend/views/list.py, material/templatetags/material_form.py, material/templatetags/material_form_internal.py
Django 3.1 removed the compatibility imporst in django.forms.forms.
=> Fix forms imports for Django 3.1

material/frontend/views/list.py
Dear all,
I think a line in `list.py` should be changed as proposed. The documentation in https://docs.djangoproject.com/en/3.1/ref/models/querysets/#django.db.models.query.QuerySet.order_by indicates that "-" should be used for a descending order, not ascending.
Without this change, the rows in `DataTable` objects are sorted in the opposite direction.
Please feel free to accept or decline the PR as you see fit.
=> Update `DataTableMixin` to handle ordering
